name: Build and Upload

on: [workflow_dispatch]

jobs:
 build-bin:
   name: Build tmux static And Upload Release
   runs-on: ubuntu-latest
   steps:
    - name: Clone
      id: checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Configuring Shell Scripts
      run: |
        chmod +x *.sh
    - name: Install Dependencies
      run: |
        ./Prepare_Compile_Env.sh
    - name: Compiling static binaries
      id: make_build
      run: |
        ./Compile.sh
    - name: Packaging binaries
      run: |
        ./Package.sh
    - name: Set variables
      run: |
        Tmux_Version=$(cat tmux_version.data)
        echo "VERSION=$Tmux_Version" >> $GITHUB_ENV
    - name: Make And Upload Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: false
        name: Tmux Static ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        files: |
          ./Tmux-Static*
        token: ${{ secrets.RELEASE_TOKEN }}
